#!/bin/bash
#SBATCH --job-name=makedb
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH -p QUEUE
#SBATCH -t 2:00:00

SECONDS=0
# Use BLAST+ version 2.14
# Install from: https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/
export PATH=$PATH:/home/erkonin/daily_notes/BLAST/ncbi-blast-2.14.1+/bin

rm -f fungi.db*
cat *.fasta > all_species.all_fasta
makeblastdb -input_type fasta -in all_species.all_fasta -blastdb_version 5 -title "grouping fungi" -dbtype nucl -out fungi.db
echo Elapsed Time: $SECONDS seconds
