#!/bin/bash
#SBATCH --job-name=parse_blast
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH -p QUEUE
#SBATCH -t 2:00:00

SECONDS=0
# check if script is started via SLURM or bash
# if with SLURM: there variable '$SLURM_JOB_ID' will exist
# `if [ -n $SLURM_JOB_ID ]` checks if $SLURM_JOB_ID is not an empty string
if [ -n $SLURM_JOB_ID ];  then
    # check the original location through scontrol and $SLURM_JOB_ID
    SCRIPT_PATH=$(scontrol show job $SLURM_JOBID | awk -F= '/Command=/{print $2}' | cut -d' ' -f1)
else
    # otherwise: started with bash. Get the real location.
    SCRIPT_PATH=$(realpath $0)
fi

# getting location of software_name 
SHARED_PATH=$(dirname ${SCRIPT_PATH})

time python -u ${SHARED_PATH}/parse_tabular_blast.py blast_results*.tab blast_

# Remove first file, which typically has too many matches
#wc -l blast_0.seq_list
#rm blast_0.seq_list
echo Elapsed Time: $SECONDS seconds
