#!/bin/sh
#SBATCH --job-name=raxml
#SBATCH --nodes=1
#SBATCH --ntasks=1

export PATH=$PATH:/home/erkonin/daily_notes/raxml-ng/build/bin:/home/erkonin/daily_notes/gene_trees

if [ "$SLURM_ARRAY_TASK_ID" == "" ]; then
        SLURM_ARRAY_TASK_ID=0
fi

input_files=(seq.list.part.*)
INPUT_FILE=${input_files[$SLURM_ARRAY_TASK_ID]}

while read input; do
	# remove illegal parts of gene names
	sed -i 's/_gene:.*$//g' ${input}
	sed -i 's/_CDS:.*$//g' ${input}
	sed -i 's/_ORF:.*$//g' ${input}
	seqkit rmdup -n ${input} > ${input}.tmp
	mv ${input}.tmp ${input}
	raxml-ng --search1 --msa ${input} --model GTR+G --prefix ${input} && rm ${input}
done < ${INPUT_FILE}
